Feature/delete character with graphql
per-wat/Intern-Project pull request #14
Opened 2023-07-06 05:55 UTC by per-wat

2023-07-06 05:58 UTC, per-wat commented on src/components/CharactersPage/CharacterForm/CharacterForm.js
> +  }, [isEdit, params])
This part of the code is used to disable the user from fetching deleted character by going back in the browser, (as in go to previous page) which will initiate the query `GET_CHARACTER` inside the form

2023-07-07 02:38 UTC, jbyomuhangi requested changes

2023-07-07 02:38 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +    })
This removes the object from the cache entirely, but other queries may still be using that object which will cause errors. You need to be removing the object from the specific query

2023-07-07 02:38 UTC, jbyomuhangi commented on src/components/CharactersPage/CharacterForm/CharacterForm.js
> +      const cachedCharacters = client.cache.extract()
You should defiantly not be doing this. The `extract` method returns a normalised version of everything in the cache, and you certainly shouldn't be reading everything in the cache. Also, what happens if a character is removed while the form is open?

2023-07-11 05:07 UTC, jbyomuhangi requested changes

2023-07-11 05:07 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
>    const handleOnClick = () => {
Please use. better function name

2023-07-11 05:07 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +    })
Please make use of the `modify` function instead here

2023-07-13 04:03 UTC, jbyomuhangi requested changes

2023-07-13 04:03 UTC, jbyomuhangi commented on src/components/CharactersPage/CharacterForm/CharacterForm.js
> +import { has } from "lodash"
unused import

2023-07-13 04:03 UTC, jbyomuhangi commented on src/components/CharactersPage/CharactersPage.js
> +
Good!

2023-07-13 04:03 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +    client.cache.modify({
Very good usage of `cache.modify` !

2023-07-13 04:03 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +          const characterToDelete = `Person:${character.id}`
We agreed to put data object names in an enum correct?

2023-07-14 05:44 UTC, jbyomuhangi requested changes

2023-07-14 05:44 UTC, jbyomuhangi commented on src/enums/__typenameEnum.js
> +export const __typenameEnum = Object.freeze({
our variable names do not start with underscores

2023-07-14 05:44 UTC, jbyomuhangi commented on src/enums/__typenameEnum.js
> +  Person: "Person",
Property names should be in camelCase

2023-07-14 05:44 UTC, jbyomuhangi commented on src/enums/__typenameEnum.js
This is not the naming convention we have for our file names

2023-07-14 05:44 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +        __typename: "Query",
This should be in your enum too no?

2023-07-17 03:22 UTC, jbyomuhangi requested changes

2023-07-17 03:22 UTC, jbyomuhangi commented on src/enums/typeNameEnum.js
> +  Query: "Query",
as mentioned before, please adhere to naming conventions for property names in objects, use **camelCase**

2023-07-17 03:22 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +          const characterToDelete = `${typeNameEnum.Person}:${character.id}`
You should be using `cache.identify` here too no?

2023-07-17 06:52 UTC, jbyomuhangi requested changes

2023-07-17 06:52 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +          })
Yous should actually be passing in the entire `character` object and let Apollo do it's thing instead of only providing these two properties

2023-07-17 06:53 UTC, jbyomuhangi commented on src/components/CharactersPage/DeleteCharacterModal/DeleteCharacterModal.js
> +          })
Same applies for your `onSubmit` function is `CharachterForm.js`

2023-07-17 09:11 UTC, jbyomuhangi approved these changes
Good!

2023-07-17 10:58 UTC, merged